### ISSUE TITLE
Could you please publish a new version of leptos_sse on crates.io

### ISSUE THREAD

**Issue by LouneCode** [messense/leptos_sse#10]
Could  You please publish a new version of leptos_sse on crates.io which includes lates changes? <br> Currently from the crates.io  can be found leptos_sse version 0.3.0 which not include lates commits of the  [Feat: upgrade dependencies: axum to 0.7 and leptos 0.6. Fix axum- and actix-examples (#8)](https://github.com/messense/leptos_sse/commit/c73ece8c3e67399243b1db754f0a9c56371c1e72)

**Comment by messense** [comment]
Done.

**Comment by LouneCode** [comment]
Thank You very much.
